version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    profiles:
      - qdrant
      - full-stack
    ports:
      - "${QDRANT_PORT_HTTP:-6333}:6333"  # HTTP API
      - "${QDRANT_PORT_GRPC:-6334}:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - ragops-network

  rag-service:
    image: donkitai/rag-service:latest
    pull_policy: always
    container_name: rag-service
    profiles:
      - rag-service
      - full-stack
    ports:
      - "${RAG_SERVICE_PORT:-8000}:8000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - ragops-network

volumes:
  qdrant_data:
    driver: local

networks:
  ragops-network:
    driver: bridge
